apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds
  labels:
    app: ds
    project: 10n1
spec:
  selector:
    matchLabels:
      app: ds
      project: 10n1
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ds
        project: 10n1
    spec:
      serviceAccountName: 10n1
      containers:
        - name: ds
          image: ghcr.io/tikalk/ds-10n1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: DB_HOST
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: DB_PASS
