apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  namespace: 10n1
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: registry-credentials
spec:
  template:
    type: kubernetes.io/dockerconfigjson
  backendType: secretsManager
  region: eu-central-1
  data:
    - key: gitlab/tokens
      name: .dockerconfigjson
      property: dockerconfigjson


