apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - es-registry-credentials-10n1.yaml
  - deploy-ds.yaml
  - deploy-ui.yaml
  - ingress.yaml
  - sa.yaml
  - svc-ds.yaml
  - svc-ui.yaml
