name: CI using github registry for dev.

on:
  pull_request:
    branches: 
      - dev
  push:
    branches: 
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build UI docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/ui-10n1:${{ github.sha }} -f UI.Dockerfile .

    - name: Build DS docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/ds-10n1:${{ github.sha }} -f DS.Dockerfile .

    - name: Log in to Github Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/ui-10n1:${{ github.sha }}

    - name: Push docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/ds-10n1:${{ github.sha }}
